export const STUDENT_ROUTES = {
  dashboard: "/student/dashboard",
  aiChat: "/student/ai-chat",
  aiChatConversation: (conversationId: string) => `/student/ai-chat/${conversationId}`,
  courses: "/student/courses",
  courseDetails: (courseId: string) => `/student/courses/${courseId}`,
  lesson: (courseId: string, lessonId: string) => `/student/courses/${courseId}/lessons/${lessonId}`,
  assignments: "/student/assignments",
  assignmentDetails: (assignmentId: string) => `/student/assignments/${assignmentId}`,
  quizzes: "/student/quizzes",
  quizAttempt: (quizId: string) => `/student/quizzes/${quizId}`,
  exams: "/student/exams",
  grades: "/student/grades",
  payments: "/student/payments",
  attendance: "/student/attendance",
  timetable: "/student/timetable",
  certificates: "/student/certificates",
  progress: "/student/progress",
  announcements: "/student/announcements",
  settings: "/student/settings",
} as const;
