export const TUTOR_ROUTES = {
  dashboard: "/tutor/dashboard",
  courses: "/tutor/courses",
  courseBuilder: (courseId: string) => `/tutor/courses/${courseId}/builder`,
  newCourse: "/tutor/courses/new",
  lessons: (courseId: string) => `/tutor/courses/${courseId}/lessons`,
  lesson: (courseId: string, lessonId: string) => `/tutor/courses/${courseId}/lessons/${lessonId}`,
  students: "/tutor/students",
  assignments: "/tutor/assignments",
  assignmentSubmissions: (assignmentId: string) => `/tutor/assignments/${assignmentId}`,
  quizzes: "/tutor/quizzes",
  exams: "/tutor/exams",
  gradebook: "/tutor/gradebook",
  attendance: "/tutor/attendance",
  announcements: "/tutor/announcements",
  schedule: "/tutor/schedule",
  reports: "/tutor/reports",
  knowledgeBase: "/tutor/knowledge-base",
  settings: "/tutor/settings",
} as const;
